### ISSUE TITLE
not working with nil data

### ISSUE THREAD

**Issue by francescob** [ankane/outliertree#2]
I'm trying to use this gem to automate some outlier detection in a rails app, so I'm trying to pass data directly from an active record query using this syntax:
`MyModel.all.to_a.map(&:serializable_hash)`
`model = OutlierTree.new`
`model.fit(data)`

and getting:

`TypeError (can't convert nil into Float)`

**Comment by ankane** [comment]
Hi @francescob, thanks for reporting! Fixed on master.
