### ISSUE TITLE
Enhance README example?

### ISSUE THREAD

**Issue by MatheusRich** [ankane/outliertree#4]
Hi @ankane! I tried to give this gem a try with the example on README, but I don't know if this is working as expected. Here's my code:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  source 'http://rubygems.org'

  gem 'outliertree'
end

data = [
  { department: 'Books',  sale: false, price: 2.50 },
  { department: 'Books',  sale: true,  price: 3.00 },
  { department: 'Movies', sale: false, price: 5.00 }
]

model = OutlierTree.new
model.fit(data)

pp model.outliers(data)
# => []

# Shouldn't it give me a string output? Is an empty array expected?
```

**Ruby version:** ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by ankane** [comment]
Hey @MatheusRich, you'll need to pass more data to get outliers (the example just shows the data format).
